modLoader="javafml"
loaderVersion="[47,)"
license="GNU LGPLv3"
[[mods]]
modId="geysermod"
version="${file.jarVersion}"
displayName="Geyser Mod"
authors="SappyInsane"
description='''
Adds geysers.
'''
[[dependencies.geysermod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.geysermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"