modLoader="javafml"
loaderVersion="[38,)"
license="GNU LGPLv3"
[[mods]]
modId="geysermod"
version="${file.jarVersion}"
displayName="Geyser Mod"
authors="SappyInsane"
description='''
Adds geysers.
'''
[[dependencies.geysermod]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.geysermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"