modLoader="javafml"
loaderVersion="[41,)"
license="GNU LGPLv3"
[[mods]]
modId="geysermod"
version="${file.jarVersion}"
displayName="Geyser Mod"
authors="SappyInsane"
description='''
Adds geysers.
'''
[[dependencies.geysermod]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.geysermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"